language: python
python:
    - "2.7"
    - "3.4"
install:
    - "pip install tox"
    - "pip install coveralls"
script:
    - "tox -e pep8"
    - "tox -e py27"
    - "tox -e py34"
after_success:
    - coveralls
notifications:
    email:
        - cedric.zhuang@emc.com
        - yue.zhao2@emc.com
        - peter.wang13@emc.com
        - tina.tang@emc.com
        - ryan.liang@emc.com