VNXSystem:
  data_src: cli
  properties:
    - label: "Model:"
    - label: "Serial No:"
      key: serial
    - label: "Revision:"
    - label: "Model Type:"
    - label: "Agent Rev:"
    - label: "Name:"


VNXNdu:
  data_src: cli
  properties:
    - label: "Name of the software package:"
      is_index: True
      key: name
    - label: "Revision of the software package:"
      key: revision
    - label: "Commit Required:"
      converter: str_to_boolean
    - label: "Revert Possible:"
      converter: str_to_boolean
    - label: "Active State:"
      converter: str_to_boolean
    - label: "Is installation completed:"
      converter: str_to_boolean
    - label: "Is this System Software:"
      converter: str_to_boolean


VNXSP:
  data_src: cli
  properties:
    - label: "SP ([AB])"
      is_index: True
      is_regex: True
      key: name
    - label: "Revision Number For the SP:"
      key: revision
    - label: "Serial Number For The SP:"
      key: serial
    - label: "Memory Size For The SP:"
      key: memory_size


VNXDomainMember:
  data_src: cli
  properties:
    - label: "IP Address:"
      is_index: True
    - label: "Name:"
    - label: "Port:"
    - label: "Secure Port:"


VNXPool:
  data_src: cli
  properties:
    - label: "Pool Name:"
      is_index: True
      key: name
    - label: "Pool ID:"
      converter: int
    - label: "Percent Full Threshold:"
      converter: float
    - label: "State:"
    - label: "Status:"
    - label: "Current Operation:"
    - label: "Current Operation State:"
    - label: "Current Operation Status:"
    - label: "Current Operation Percent Completed:"
      converter: float
    - label: "User Capacity (GBs):"
      converter: float
    - label: "Consumed Capacity (GBs):"
      converter: float
    - label: "Available Capacity (GBs):"
      converter: float
    - label: "Total Subscribed Capacity (GBs):"
      converter: float
    - label: "LUNs:"
      converter: str_to_int_arr
    - label: "FAST Cache:"
      converter: str_to_boolean


VNXConsistencyGroup:
  data_src: cli
  properties:
    - label: "Name:"
      is_index: True
    - label: "Member LUN ID(s):"
      key: lun_list
      converter: str_to_int_arr
    - label: "State:"


VNXPoolFeature:
  data_src: cli
  properties:
    - label: "Max. Pool LUNs:"
      option: -maxPoolLUNs
      converter: int
    - label: "Total Number of Pool LUNs:"
      key: total_pool_luns
      option: -numPoolLUNs
      converter: int
  default: max_pool_luns, total_pool_luns


VNXLun:
  data_src: cli
  properties:
    - label: "Current State:"
      key: state
      option: -state
    - label: "UID:"
      key: wwn
      option: -uid
    - label: "Status:"
      option: -status
    - label: "Current Operation:"
      key: operation
      option: -opDetails
    - label: "User Capacity (GBs):"
      key: total_capacity_gb
      option: -userCap
      converter: float
    - label: "Current Owner:"
      option: -owner
      converter: to_sp_enum
    - label: "Default Owner:"
      converter: to_sp_enum
    - label: "Attached Snapshot:"
      option: -attachedSnapshot
    - label: "Name:"
    - label: LOGICAL UNIT NUMBER
      key: lun_id
      converter: int
      is_index: True
    - label: "Pool Name:"
      option: -poolName
    - label: "Is Thin LUN:"
      option: -isThinLUN
      converter: str_to_boolean
    - label: "Is Compressed:"
      option: -isCompressed
      converter: str_to_boolean
    - label: "Deduplication State:"
      option: -dedupState
      key: is_dedup
      converter: str_to_boolean
    - label: "Initial Tier:"
      option: -initialTier
    - label: "Tiering Policy:"
      option: -tieringPolicy
    - label: "Is Private:"
      option: -isPrivate
      converter: str_to_boolean
    - label: "User Capacity (GBs):"
      converter: float
    - label: "Consumed Capacity (GBs):"
      converter: float
    - label: "Snapshot Mount Points:"
      converter: str_to_int_arr
    - label: "Attached Snapshot:"


VNXSPPort:
  data_src: cli
  properties:
    - label: "SP Name:"
      is_index: True
      key: sp
      converter: to_sp_enum
    - label: "SP Port ID:"
      is_index: True
      key: port_id
      converter: int
    - label: "SP UID:"
      key: wwn
    - label: "Link Status:"
    - label: "Port Status:"
    - label: "Switch Present:"
      converter: str_to_boolean
    - label: "Speed Value :"
    - label: "Registered Initiators:"
      converter: int
    - label: "Logged-In Initiators:"
      converter: int
    - label: "Not Logged-In Initiators:"
      converter: int


VNXStorageGroup:
  data_src: cli
  properties:
    - label: "Storage Group Name:"
      key: name
      is_index: True
      option: -gname
    - label: "Storage Group UID:"
      key: wwn
      option: -uid
    - label: "Shareable:"
      converter: str_to_boolean
    - label: "HLU/ALU Pairs:"
      key: alu_hlu_map
      converter: to_alu_hlu_map
      end_pattern: "Shareable"
    - label: "HBA/SP Pairs:"
      converter: VNXStorageGroupHBAList
      end_pattern: "HLU/ALU Pairs:"


VNXStorageGroupHBA:
  data_src: cli
  properties:
    - label:  |
        ^\s*(\S+)\s+(SP \w)\s+(\d+)\s*$
      is_index: True
      is_regex: True
      key: hba
    - label: "Host name:"
    - label: "SPPort:"
    - label: "Initiator IP:"
    - label: "TPGT:"
    - label: "ISID:"


VNXConnectionPort:
  data_src: cli
  properties:
    - label: "SP:"
      is_index: True
      converter: to_sp_enum
    - label: "Port ID:"
      is_index: True
      converter: int
    - label: "Port WWN:"
      key: wwn
    - label: "iSCSI Alias:"
      key: iscsi_alias
    - label: "Enode MAC Address:"
    - label: "Port Speed:"
    - label: "Auto-Negotiate:"
      converter: str_to_boolean
    - label: "Available Speed:"
    - label: "Current MTU:"
      converter: int
    - label: "Flow Control:"
    - label: "Host Window:"
    - label: "Replication Window:"
    - label: "Virtual Port ID:"
      converter: int
    - label: "VLAN ID:"
      converter: int
    - label: "IP Address:"
    - label: "Subnet Mask:"
    - label: "Gateway Address:"
    - label: "Initiator Authentication:"


VNXSnap:
  data_src: cli
  properties:
    - label: "Name:"
      is_index: True
    - label: "Description:"
    - label: "Creation time:"
    - label: "Last modify time:"
    - label: "Last modified by:"
    - label: "Source LUN(s):"
      converter: str_to_int_arr
    - label: "Source CG:"
    - label: "Primary LUN(s):"
      converter: str_to_int_arr
    - label: "State:"
    - label: "Status:"
    - label: "Allow Read/Write:"
      converter: str_to_boolean
    - label: "Modified:"
      converter: str_to_boolean
    - label: "Attached LUN(s):"
      converter: str_to_int_arr
    - label: "Allow auto delete:"
      converter: str_to_boolean
    - label: "Expiration date:"


VNXMigrationSession:
  data_src: cli
  properties:
    - label: "Source LU Name:"
      is_index: True
    - label: "Source LU ID:"
      converter: int
    - label: "Dest LU Name:"
    - label: "Dest LU ID:"
      converter: int
    - label: "Migration Rate:"
    - label: "Current State:"
    - label: "Percent Complete:"
      converter: float
    - label: "Time Remaining:"
